import 'dotenv/config';
import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { hashPassword, loginSchema, readToken, registerSchema, signToken, verifyPassword } from './auth.js';
import { assertTransition, purchaseUpdateSchema, stockRequestSchema } from './tuckquest.js';
import { currentStock, productSchema, saleSchema, saleTotals } from './kasibiz.js';
import { calculateCommission, getPaymentProvider, paymentRequestSchema, signedAmount } from './wallet.js';
import { assertServiceTransition, providerSchema, quoteSchema, quoteTotal, requestSchema } from './mzansifix.js';
import { expectedPayment, jobSchema, matchScore, workedMinutes, workerSchema } from './mzansiwork.js';
import { orderTotal, supplierOrderSchema, supplierProductSchema, supplierProfileSchema } from './suppliers.js';
const db=new PrismaClient(); const app=express();
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'64kb',verify:(req:any,_res,buf)=>{req.rawBody=buf.toString('utf8')}})); app.use(cookieParser());
const asyncRoute=(fn:any)=>(req:any,res:any,next:any)=>Promise.resolve(fn(req,res,next)).catch(next);
const current=asyncRoute(async(req:any,res:any,next:any)=>{const token=req.cookies.hydra_session;if(!token)return res.status(401).json({error:'Authentication required'});try{const claims=readToken(token);req.identity=claims;next();}catch{return res.status(401).json({error:'Session expired'});}});
app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'hydra-core'}));
app.post('/api/auth/register',asyncRoute(async(req:any,res:any)=>{const input=registerSchema.parse(req.body);const exists=await db.user.findFirst({where:{OR:[{email:input.email.toLowerCase()},{phone:input.phone}]}});if(exists)return res.status(409).json({error:'Email or phone is already registered'});const user=await db.$transaction(async tx=>{const created=await tx.user.create({data:{email:input.email.toLowerCase(),phone:input.phone,firstName:input.firstName,lastName:input.lastName,passwordHash:await hashPassword(input.password),roles:{create:{role:input.role}}},include:{roles:true}});await tx.auditLog.create({data:{action:'USER_REGISTERED',entity:'User',entityId:created.id,userId:created.id}});return created;});const roles=user.roles.map(r=>r.role);res.cookie('hydra_session',signToken({sub:user.id,roles}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}).status(201).json({user:safe(user),roles});}));
app.post('/api/auth/login',asyncRoute(async(req:any,res:any)=>{const input=loginSchema.parse(req.body);const user=await db.user.findUnique({where:{email:input.email.toLowerCase()},include:{roles:true}});if(!user||!await verifyPassword(input.password,user.passwordHash))return res.status(401).json({error:'Invalid email or password'});if(user.status!=='ACTIVE')return res.status(403).json({error:'Account is not active'});const roles=user.roles.map(r=>r.role);res.cookie('hydra_session',signToken({sub:user.id,roles}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}).json({user:safe(user),roles});}));
app.post('/api/auth/logout',(_req,res)=>res.clearCookie('hydra_session').status(204).end());
app.get('/api/me',current,asyncRoute(async(req:any,res:any)=>{const user=await db.user.findUniqueOrThrow({where:{id:req.identity.sub},include:{roles:true,businesses:{include:{business:true}}}});res.json({user:safe(user),roles:user.roles.map(r=>r.role),businesses:user.businesses.map(m=>m.business)});}));
const businessSchema=z.object({name:z.string().min(2).max(120),registrationNumber:z.string().max(50).optional(),address:z.string().max(240).optional()});
app.post('/api/businesses',current,asyncRoute(async(req:any,res:any)=>{const input=businessSchema.parse(req.body);const business=await db.$transaction(async tx=>{const b=await tx.business.create({data:{...input,members:{create:{userId:req.identity.sub,role:'OWNER'}}}});await tx.auditLog.create({data:{action:'BUSINESS_CREATED',entity:'Business',entityId:b.id,userId:req.identity.sub}});return b;});res.status(201).json({business});}));
app.get('/api/admin/overview',current,asyncRoute(async(req:any,res:any)=>{if(!req.identity.roles.some((r:string)=>['ADMIN','SUPER_ADMIN'].includes(r)))return res.status(403).json({error:'Administrator role required'});const [users,businesses,pending]=await Promise.all([db.user.count(),db.business.count(),db.business.count({where:{verificationStatus:'PENDING'}})]);res.json({users,businesses,pending});}));
app.post('/api/tuckquest/drivers',current,asyncRoute(async(req:any,res:any)=>{const input=z.object({address:z.string().min(5),licenceNumber:z.string().min(3),licenceExpiry:z.string().datetime(),vehicleMake:z.string().min(2),vehicleModel:z.string().min(1),registration:z.string().min(3),vehicleType:z.string().min(2),vehicleColour:z.string().min(2),vehiclePhotoUrl:z.string().url().optional(),documentRefs:z.string().optional(),paymentProfileRef:z.string().optional()}).parse(req.body);const data={...input,licenceExpiry:new Date(input.licenceExpiry),verificationStatus:'PENDING' as const};const profile=await db.driverProfile.upsert({where:{userId:req.identity.sub},update:data,create:{...data,userId:req.identity.sub}});res.status(201).json({profile});}));
app.patch('/api/tuckquest/drivers/me/location',current,asyncRoute(async(req:any,res:any)=>{const input=z.object({isOnline:z.boolean(),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional()}).parse(req.body);const profile=await db.driverProfile.findUniqueOrThrow({where:{userId:req.identity.sub}});if(input.isOnline&&profile.verificationStatus!=='VERIFIED')return res.status(403).json({error:'Only verified drivers may go online'});res.json({profile:await db.driverProfile.update({where:{userId:req.identity.sub},data:input})});}));
app.post('/api/tuckquest/requests',current,asyncRoute(async(req:any,res:any)=>{const input=stockRequestSchema.parse(req.body);const member=await db.businessMember.findUnique({where:{businessId_userId:{businessId:input.businessId,userId:req.identity.sub}}});if(!member)return res.status(403).json({error:'You do not manage this business'});const estimatedTotalCents=input.items.reduce((sum,item)=>sum+item.quantity*item.estimatedUnitCents,0);const request=await db.stockRequest.create({data:{businessId:input.businessId,supplierName:input.supplierName,notes:input.notes,deliveryAddress:input.deliveryAddress,allowAlternative:input.allowAlternative,estimatedTotalCents,status:'SEARCHING_DRIVER',items:{create:input.items}},include:{items:true}});res.status(201).json({request});}));
app.get('/api/tuckquest/requests',current,asyncRoute(async(req:any,res:any)=>{const driver=await db.driverProfile.findUnique({where:{userId:req.identity.sub}});const where=driver?.verificationStatus==='VERIFIED'&&driver.isOnline?{OR:[{driverId:req.identity.sub},{status:'SEARCHING_DRIVER' as const}]}:{business:{members:{some:{userId:req.identity.sub}}}};res.json({requests:await db.stockRequest.findMany({where,include:{items:true,business:true},orderBy:{createdAt:'desc'}})});}));
app.post('/api/tuckquest/requests/:id/accept',current,asyncRoute(async(req:any,res:any)=>{const driver=await db.driverProfile.findUnique({where:{userId:req.identity.sub}});if(!driver||driver.verificationStatus!=='VERIFIED'||!driver.isOnline)return res.status(403).json({error:'A verified online driver is required'});const claimed=await db.stockRequest.updateMany({where:{id:req.params.id,status:'SEARCHING_DRIVER',driverId:null},data:{driverId:req.identity.sub,status:'DRIVER_ASSIGNED'}});if(claimed.count!==1)return res.status(409).json({error:'Request is no longer available'});res.json({request:await db.stockRequest.findUnique({where:{id:req.params.id},include:{items:true}})});}));
app.post('/api/tuckquest/requests/:id/start-shopping',current,asyncRoute(async(req:any,res:any)=>{const request=await ownDriverRequest(req.params.id,req.identity.sub);assertTransition(request.status,'SHOPPING');res.json({request:await db.stockRequest.update({where:{id:request.id},data:{status:'SHOPPING'}})});}));
app.post('/api/tuckquest/requests/:id/prices',current,asyncRoute(async(req:any,res:any)=>{const input=purchaseUpdateSchema.parse(req.body);const request=await ownDriverRequest(req.params.id,req.identity.sub);assertTransition(request.status,'AWAITING_APPROVAL');const itemMap=new Map(request.items.map(item=>[item.id,item]));let actualTotalCents=0;await db.$transaction(async tx=>{for(const change of input.items){const item=itemMap.get(change.id);if(!item)throw Object.assign(new Error('Item does not belong to request'),{status:400});await tx.stockRequestItem.update({where:{id:item.id},data:change});if(!change.unavailable)actualTotalCents+=(change.actualUnitCents??0)*item.quantity}await tx.stockRequest.update({where:{id:request.id},data:{receiptUrl:input.receiptUrl,actualTotalCents,status:'AWAITING_APPROVAL'}})});res.json({request:await db.stockRequest.findUnique({where:{id:request.id},include:{items:true}})});}));
app.post('/api/tuckquest/requests/:id/approval',current,asyncRoute(async(req:any,res:any)=>{const {approved}=z.object({approved:z.boolean()}).parse(req.body);const request=await ownBusinessRequest(req.params.id,req.identity.sub);const next=approved?'PURCHASED':'SHOPPING';assertTransition(request.status,next);res.json({request:await db.stockRequest.update({where:{id:request.id},data:{status:next,ownerApprovedAt:approved?new Date():null}})});}));
app.post('/api/tuckquest/requests/:id/delivering',current,asyncRoute(async(req:any,res:any)=>{const request=await ownDriverRequest(req.params.id,req.identity.sub);assertTransition(request.status,'DELIVERING');const pin=String(Math.floor(100000+Math.random()*900000));res.json({request:await db.stockRequest.update({where:{id:request.id},data:{status:'DELIVERING',deliveryPinHash:await hashPassword(pin)}}),deliveryPin:pin});}));
app.post('/api/tuckquest/requests/:id/arrived',current,asyncRoute(async(req:any,res:any)=>{const request=await ownDriverRequest(req.params.id,req.identity.sub);assertTransition(request.status,'ARRIVED');res.json({request:await db.stockRequest.update({where:{id:request.id},data:{status:'ARRIVED'}})});}));
app.post('/api/tuckquest/requests/:id/confirm',current,asyncRoute(async(req:any,res:any)=>{const {pin}=z.object({pin:z.string().length(6)}).parse(req.body);const request=await ownBusinessRequest(req.params.id,req.identity.sub);assertTransition(request.status,'DELIVERED');if(!request.deliveryPinHash||!await verifyPassword(pin,request.deliveryPinHash))return res.status(400).json({error:'Invalid delivery PIN'});const delivered=await db.$transaction(async tx=>{const updated=await tx.stockRequest.update({where:{id:request.id},data:{status:'DELIVERED',deliveryPinHash:null}});for(const item of request.items){if(item.unavailable)continue;const product=await tx.product.findFirst({where:{businessId:request.businessId,name:item.productName}});if(product)await tx.inventoryMovement.create({data:{productId:product.id,type:'PURCHASE',quantityDelta:item.quantity,unitCostCents:item.actualUnitCents,reference:request.receiptUrl,sourceRequestId:request.id}})}await tx.expense.create({data:{businessId:request.businessId,category:'STOCK_PURCHASE',supplier:request.supplierName,amountCents:request.actualTotalCents??request.estimatedTotalCents,reference:request.receiptUrl}});await tx.supplierOrder.updateMany({where:{stockRequestId:request.id},data:{status:'DELIVERED'}});return updated});res.json({request:delivered});}));
app.post('/api/tuckquest/requests/:id/reviews',current,asyncRoute(async(req:any,res:any)=>{const input=z.object({subjectId:z.string(),rating:z.number().int().min(1).max(5),comment:z.string().max(500).optional()}).parse(req.body);const request=await db.stockRequest.findUniqueOrThrow({where:{id:req.params.id},include:{business:{include:{members:true}}}});if(request.status!=='DELIVERED')return res.status(409).json({error:'Only delivered requests may be reviewed'});if(!(request.driverId===req.identity.sub||request.business.members.some(member=>member.userId===req.identity.sub)))return res.status(403).json({error:'Only transaction participants may review'});res.status(201).json({review:await db.review.create({data:{requestId:request.id,authorId:req.identity.sub,subjectId:input.subjectId,rating:input.rating,comment:input.comment}})});}));
app.post('/api/kasibiz/products',current,asyncRoute(async(req:any,res:any)=>{const input=productSchema.parse(req.body);await requireBusiness(input.businessId,req.identity.sub);const {openingQuantity,...data}=input;const product=await db.$transaction(async tx=>{const created=await tx.product.create({data});if(openingQuantity)await tx.inventoryMovement.create({data:{productId:created.id,type:'ADJUSTMENT',quantityDelta:openingQuantity,reference:'OPENING_STOCK'}});return created});res.status(201).json({product});}));
app.get('/api/kasibiz/products/:businessId',current,asyncRoute(async(req:any,res:any)=>{await requireBusiness(req.params.businessId,req.identity.sub);const products=await db.product.findMany({where:{businessId:req.params.businessId},include:{movements:true}});res.json({products:products.map(product=>({...product,quantity:currentStock(product.movements)}))});}));
app.post('/api/kasibiz/sales',current,asyncRoute(async(req:any,res:any)=>{const input=saleSchema.parse(req.body);await requireBusiness(input.businessId,req.identity.sub);const products=await db.product.findMany({where:{id:{in:input.items.map(item=>item.productId)},businessId:input.businessId},include:{movements:true}});if(products.length!==new Set(input.items.map(item=>item.productId)).size)return res.status(400).json({error:'One or more products are invalid'});const lines=input.items.map(item=>{const product=products.find(p=>p.id===item.productId)!;if(currentStock(product.movements)<item.quantity)throw Object.assign(new Error(`Insufficient stock for ${product.name}`),{status:409});return{...item,unitPriceCents:product.sellingPriceCents}});const totals=saleTotals(lines,input.discountCents);const sale=await db.$transaction(async tx=>{const created=await tx.sale.create({data:{businessId:input.businessId,paymentMethod:input.paymentMethod,...totals,items:{create:lines.map(line=>({productId:line.productId,quantity:line.quantity,unitPriceCents:line.unitPriceCents}))}}});for(const line of lines)await tx.inventoryMovement.create({data:{productId:line.productId,type:'SALE',quantityDelta:-line.quantity,reference:created.id}});return created});res.status(201).json({sale});}));
app.post('/api/kasibiz/sales/:id/refund',current,asyncRoute(async(req:any,res:any)=>{const sale=await db.sale.findUniqueOrThrow({where:{id:req.params.id},include:{items:true}});await requireBusiness(sale.businessId,req.identity.sub);if(sale.refundedAt)return res.status(409).json({error:'Sale already refunded'});await db.$transaction(async tx=>{await tx.sale.update({where:{id:sale.id},data:{refundedAt:new Date()}});for(const item of sale.items)await tx.inventoryMovement.create({data:{productId:item.productId,type:'RETURN',quantityDelta:item.quantity,reference:sale.id}})});res.status(204).end();}));
app.get('/api/kasibiz/dashboard/:businessId',current,asyncRoute(async(req:any,res:any)=>{await requireBusiness(req.params.businessId,req.identity.sub);const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),dayStart=new Date(now.getFullYear(),now.getMonth(),now.getDate());const [sales,expenses,products]=await Promise.all([db.sale.findMany({where:{businessId:req.params.businessId,refundedAt:null,createdAt:{gte:monthStart}}}),db.expense.findMany({where:{businessId:req.params.businessId,createdAt:{gte:monthStart}}}),db.product.findMany({where:{businessId:req.params.businessId},include:{movements:true}})]);const monthSales=sales.reduce((s,x)=>s+x.totalCents,0),expenseTotal=expenses.reduce((s,x)=>s+x.amountCents,0);res.json({todaySales:sales.filter(s=>s.createdAt>=dayStart).reduce((n,s)=>n+s.totalCents,0),monthSales,expenses:expenseTotal,estimatedProfit:monthSales-expenseTotal,lowStock:products.filter(p=>currentStock(p.movements)<=p.reorderLevel).map(p=>({...p,quantity:currentStock(p.movements)}))});}));
app.post('/api/kasibiz/low-stock/:businessId/order',current,asyncRoute(async(req:any,res:any)=>{await requireBusiness(req.params.businessId,req.identity.sub);const input=z.object({supplierName:z.string().min(2),deliveryAddress:z.string().min(5)}).parse(req.body);const products=await db.product.findMany({where:{businessId:req.params.businessId},include:{movements:true}});const low=products.filter(p=>currentStock(p.movements)<=p.reorderLevel);if(!low.length)return res.status(409).json({error:'No products are at reorder level'});const request=await db.stockRequest.create({data:{businessId:req.params.businessId,supplierName:input.supplierName,deliveryAddress:input.deliveryAddress,status:'SEARCHING_DRIVER',estimatedTotalCents:low.reduce((s,p)=>s+Math.max(1,p.reorderLevel*2-currentStock(p.movements))*p.costPriceCents,0),items:{create:low.map(p=>({productName:p.name,quantity:Math.max(1,p.reorderLevel*2-currentStock(p.movements)),estimatedUnitCents:p.costPriceCents}))}},include:{items:true}});res.status(201).json({request});}));
app.get('/api/wallet',current,asyncRoute(async(req:any,res:any)=>{const wallet=await db.wallet.upsert({where:{userId:req.identity.sub},update:{},create:{userId:req.identity.sub},include:{transactions:{orderBy:{createdAt:'desc'},take:100}}});const completed=wallet.transactions.filter(t=>t.status==='COMPLETED');res.json({wallet,balanceCents:completed.reduce((sum,t)=>sum+signedAmount(t.type,t.amountCents),0),availableCents:completed.filter(t=>t.type!=='HOLD').reduce((sum,t)=>sum+signedAmount(t.type,t.amountCents),0)});}));
app.post('/api/payments/initiate',current,asyncRoute(async(req:any,res:any)=>{const input=paymentRequestSchema.parse(req.body),provider=getPaymentProvider();const existing=await db.paymentRecord.findUnique({where:{idempotencyKey:input.idempotencyKey}});if(existing)return res.json({payment:existing});const initiated=await provider.initiate(input);const payment=await db.paymentRecord.create({data:{provider:provider.name,providerReference:initiated.providerReference,idempotencyKey:input.idempotencyKey,amountCents:input.amountCents,currency:input.currency,status:'PENDING',relatedEntityType:input.relatedEntityType,relatedEntityId:input.relatedEntityId,metadata:JSON.stringify({userId:req.identity.sub})}});res.status(201).json({payment});}));
app.post('/api/payments/webhooks/sandbox',asyncRoute(async(req:any,res:any)=>{const provider=getPaymentProvider(),signature=String(req.headers['x-hydra-signature']||'');if(!provider.verifyWebhook(req.rawBody||'',signature))return res.status(401).json({error:'Invalid webhook signature'});const event=z.object({providerReference:z.string(),status:z.enum(['SUCCEEDED','FAILED'])}).parse(req.body);const payment=await db.paymentRecord.findUniqueOrThrow({where:{providerReference:event.providerReference}});if(payment.status==='SUCCEEDED'||payment.status==='FAILED')return res.status(204).end();await db.$transaction(async tx=>{await tx.paymentRecord.update({where:{id:payment.id},data:{status:event.status}});if(event.status==='SUCCEEDED'){const userId=JSON.parse(payment.metadata||'{}').userId;if(!userId)throw new Error('Payment owner is missing');const wallet=await tx.wallet.upsert({where:{userId},update:{},create:{userId}});await tx.walletTransaction.create({data:{walletId:wallet.id,type:'CREDIT',amountCents:payment.amountCents,currency:payment.currency,reference:`payment:${payment.id}`,status:'COMPLETED',relatedEntityType:payment.relatedEntityType,relatedEntityId:payment.relatedEntityId}})}});res.status(204).end();}));
app.post('/api/payments/:id/refund',current,asyncRoute(async(req:any,res:any)=>{const payment=await db.paymentRecord.findUniqueOrThrow({where:{id:req.params.id}});const ownerId=JSON.parse(payment.metadata||'{}').userId;if(ownerId!==req.identity.sub)return res.status(403).json({error:'Payment ownership required'});if(payment.status!=='SUCCEEDED')return res.status(409).json({error:'Only successful payments may be refunded'});const provider=getPaymentProvider();await provider.refund(payment.providerReference!,payment.amountCents);const wallet=await db.wallet.findUniqueOrThrow({where:{userId:ownerId}});const original=await db.walletTransaction.findUniqueOrThrow({where:{reference:`payment:${payment.id}`}});await db.$transaction([db.paymentRecord.update({where:{id:payment.id},data:{status:'REFUNDED'}}),db.walletTransaction.create({data:{walletId:wallet.id,type:'DEBIT',amountCents:payment.amountCents,currency:payment.currency,reference:`refund:${payment.id}`,status:'COMPLETED',reversalOfId:original.id,relatedEntityType:payment.relatedEntityType,relatedEntityId:payment.relatedEntityId}})]);res.status(202).json({status:'REFUNDED'});}));
app.put('/api/admin/commission-rules/:service',current,asyncRoute(async(req:any,res:any)=>{if(!req.identity.roles.some((r:string)=>['ADMIN','SUPER_ADMIN'].includes(r)))return res.status(403).json({error:'Administrator role required'});const input=z.object({commissionBasisPoints:z.number().int().min(0).max(10000),paymentFeeCents:z.number().int().nonnegative(),vatBasisPoints:z.number().int().min(0).max(10000)}).parse(req.body);res.json({rule:await db.commissionRule.upsert({where:{service_active:{service:req.params.service,active:true}},update:input,create:{service:req.params.service,active:true,...input}})});}));
app.post('/api/tuckquest/requests/:id/settle',current,asyncRoute(async(req:any,res:any)=>{const request=await ownBusinessRequest(req.params.id,req.identity.sub);if(request.status!=='DELIVERED'||!request.driverId)return res.status(409).json({error:'A delivered request with an assigned driver is required'});const rule=await db.commissionRule.findUnique({where:{service_active:{service:'TUCKQUEST',active:true}}});if(!rule)return res.status(409).json({error:'TUCKQUEST commission rule is not configured'});const grossCents=z.object({grossCents:z.number().int().positive()}).parse(req.body).grossCents,snapshot=calculateCommission({grossCents,commissionBasisPoints:rule.commissionBasisPoints,paymentFeeCents:rule.paymentFeeCents,vatBasisPoints:rule.vatBasisPoints});const wallet=await db.wallet.upsert({where:{userId:request.driverId},update:{},create:{userId:request.driverId}});const reference=`tuckquest-settlement:${request.id}`;const transaction=await db.walletTransaction.create({data:{walletId:wallet.id,type:'CREDIT',amountCents:snapshot.netSettlementCents,reference,status:'COMPLETED',relatedEntityType:'StockRequest',relatedEntityId:request.id,commissionSnapshot:JSON.stringify(snapshot)}});res.status(201).json({transaction,snapshot});}));
app.get('/api/tuckquest/driver/earnings',current,asyncRoute(async(req:any,res:any)=>{const wallet=await db.wallet.findUnique({where:{userId:req.identity.sub},include:{transactions:{where:{relatedEntityType:'StockRequest'},orderBy:{createdAt:'desc'}}}});const transactions=wallet?.transactions??[],now=new Date(),day=new Date(now.getFullYear(),now.getMonth(),now.getDate()),week=new Date(day);week.setDate(day.getDate()-day.getDay());const month=new Date(now.getFullYear(),now.getMonth(),1),sum=(from:Date,status='COMPLETED')=>transactions.filter(t=>t.createdAt>=from&&t.status===status).reduce((n,t)=>n+signedAmount(t.type,t.amountCents),0);res.json({today:sum(day),thisWeek:sum(week),thisMonth:sum(month),available:transactions.filter(t=>t.status==='COMPLETED').reduce((n,t)=>n+signedAmount(t.type,t.amountCents),0),pending:transactions.filter(t=>t.status==='PENDING').reduce((n,t)=>n+t.amountCents,0),transactions,withdrawalsEnabled:false});}));
app.post('/api/mzansifix/providers',current,asyncRoute(async(req:any,res:any)=>{const input=providerSchema.parse(req.body),data={...input,categories:JSON.stringify(input.categories),skills:JSON.stringify(input.skills),portfolioRefs:JSON.stringify(input.portfolioRefs),verificationStatus:'PENDING' as const};res.status(201).json({provider:await db.serviceProvider.upsert({where:{userId:req.identity.sub},update:data,create:{...data,userId:req.identity.sub}})});}));
app.post('/api/mzansifix/requests',current,asyncRoute(async(req:any,res:any)=>{const input=requestSchema.parse(req.body),request=await db.serviceRequest.create({data:{customerId:req.identity.sub,category:input.category,description:input.description,photoRefs:JSON.stringify(input.photoRefs),address:input.address,latitude:input.latitude,longitude:input.longitude,preferredDate:input.preferredDate?new Date(input.preferredDate):undefined,urgency:input.urgency,budgetCents:input.budgetCents,transitions:{create:{fromState:null,toState:'REQUESTED',actorId:req.identity.sub}}}});res.status(201).json({request});}));
app.get('/api/mzansifix/opportunities',current,asyncRoute(async(req:any,res:any)=>{const provider=await db.serviceProvider.findUniqueOrThrow({where:{userId:req.identity.sub}});if(provider.verificationStatus!=='VERIFIED')return res.status(403).json({error:'Verified provider profile required'});const categories=JSON.parse(provider.categories) as string[];res.json({requests:await db.serviceRequest.findMany({where:{status:{in:['REQUESTED','QUOTED']},category:{in:categories}},select:{id:true,category:true,description:true,address:true,preferredDate:true,urgency:true,budgetCents:true,status:true,createdAt:true}})});}));
app.post('/api/mzansifix/requests/:id/quotes',current,asyncRoute(async(req:any,res:any)=>{const provider=await db.serviceProvider.findUniqueOrThrow({where:{userId:req.identity.sub}});if(provider.verificationStatus!=='VERIFIED')return res.status(403).json({error:'Verified provider profile required'});const input=quoteSchema.parse(req.body),request=await db.serviceRequest.findUniqueOrThrow({where:{id:req.params.id}});if(!['REQUESTED','QUOTED'].includes(request.status))return res.status(409).json({error:'Request is not accepting quotes'});const quote=await db.$transaction(async tx=>{const q=await tx.serviceQuote.upsert({where:{requestId_providerId:{requestId:request.id,providerId:provider.id}},update:{...input,totalCents:quoteTotal(input)},create:{...input,totalCents:quoteTotal(input),requestId:request.id,providerId:provider.id}});if(request.status==='REQUESTED'){await tx.serviceRequest.update({where:{id:request.id},data:{status:'QUOTED'}});await tx.serviceTransition.create({data:{requestId:request.id,fromState:'REQUESTED',toState:'QUOTED',actorId:req.identity.sub}})}return q});res.status(201).json({quote});}));
app.get('/api/mzansifix/requests/:id/quotes',current,asyncRoute(async(req:any,res:any)=>{const request=await ownServiceCustomer(req.params.id,req.identity.sub);res.json({quotes:await db.serviceQuote.findMany({where:{requestId:request.id},select:{id:true,labourCents:true,materialsCents:true,calloutCents:true,otherFeesCents:true,totalCents:true,notes:true,estimatedDurationMins:true,provider:{select:{id:true,businessName:true,verificationStatus:true,userId:true}}}})});}));
app.post('/api/mzansifix/quotes/:id/accept',current,asyncRoute(async(req:any,res:any)=>{const quote=await db.serviceQuote.findUniqueOrThrow({where:{id:req.params.id},include:{request:true}});if(quote.request.customerId!==req.identity.sub)return res.status(403).json({error:'Customer ownership required'});assertServiceTransition(quote.request.status,'ACCEPTED');const wallet=await db.wallet.findUnique({where:{userId:req.identity.sub},include:{transactions:true}}),balance=(wallet?.transactions??[]).filter(t=>t.status==='COMPLETED').reduce((n,t)=>n+signedAmount(t.type,t.amountCents),0);if(!wallet||balance<quote.totalCents)return res.status(409).json({error:'Insufficient HYDRA Wallet balance'});const request=await db.$transaction(async tx=>{await tx.walletTransaction.create({data:{walletId:wallet.id,type:'HOLD',amountCents:quote.totalCents,reference:`mzansifix-hold:${quote.requestId}`,status:'PENDING',relatedEntityType:'ServiceRequest',relatedEntityId:quote.requestId}});const updated=await tx.serviceRequest.update({where:{id:quote.requestId},data:{status:'ACCEPTED',providerId:quote.providerId,acceptedQuoteId:quote.id,paymentHoldRef:`mzansifix-hold:${quote.requestId}`}});await tx.serviceTransition.create({data:{requestId:quote.requestId,fromState:quote.request.status,toState:'ACCEPTED',actorId:req.identity.sub}});return updated});res.json({request});}));
app.post('/api/mzansifix/requests/:id/transition',current,asyncRoute(async(req:any,res:any)=>{const {status}=z.object({status:z.enum(['ON_THE_WAY','ARRIVED','WORK_STARTED','COMPLETED'])}).parse(req.body),provider=await db.serviceProvider.findUniqueOrThrow({where:{userId:req.identity.sub}}),request=await db.serviceRequest.findFirstOrThrow({where:{id:req.params.id,providerId:provider.id}});assertServiceTransition(request.status,status);res.json({request:await db.$transaction(async tx=>{const updated=await tx.serviceRequest.update({where:{id:request.id},data:{status}});await tx.serviceTransition.create({data:{requestId:request.id,fromState:request.status,toState:status,actorId:req.identity.sub}});return updated})});}));
app.post('/api/mzansifix/requests/:id/evidence',current,asyncRoute(async(req:any,res:any)=>{const provider=await db.serviceProvider.findUniqueOrThrow({where:{userId:req.identity.sub}}),request=await db.serviceRequest.findFirstOrThrow({where:{id:req.params.id,providerId:provider.id}}),input=z.object({before:z.array(z.string().url()).max(20).optional(),after:z.array(z.string().url()).max(20).optional(),completionNotes:z.string().max(2000).optional()}).parse(req.body);res.json({request:await db.serviceRequest.update({where:{id:request.id},data:{beforeEvidence:input.before?JSON.stringify(input.before):undefined,afterEvidence:input.after?JSON.stringify(input.after):undefined,completionNotes:input.completionNotes}})});}));
app.post('/api/mzansifix/requests/:id/confirm',current,asyncRoute(async(req:any,res:any)=>{const request=await ownServiceCustomer(req.params.id,req.identity.sub);assertServiceTransition(request.status,'CUSTOMER_CONFIRMED');res.json({request:await transitionService(request,'CUSTOMER_CONFIRMED',req.identity.sub)});}));
app.post('/api/mzansifix/requests/:id/release',current,asyncRoute(async(req:any,res:any)=>{const request=await ownServiceCustomer(req.params.id,req.identity.sub);assertServiceTransition(request.status,'PAYMENT_RELEASED');if(!request.providerId||!request.acceptedQuoteId||!request.paymentHoldRef)return res.status(409).json({error:'Payment hold is incomplete'});const [quote,provider,rule]=await Promise.all([db.serviceQuote.findUniqueOrThrow({where:{id:request.acceptedQuoteId}}),db.serviceProvider.findUniqueOrThrow({where:{id:request.providerId}}),db.commissionRule.findUnique({where:{service_active:{service:'MZANSIFIX',active:true}}})]);if(!rule)return res.status(409).json({error:'MZANSIFIX commission rule is not configured'});const snapshot=calculateCommission({grossCents:quote.totalCents,commissionBasisPoints:rule.commissionBasisPoints,paymentFeeCents:rule.paymentFeeCents,vatBasisPoints:rule.vatBasisPoints}),providerWallet=await db.wallet.upsert({where:{userId:provider.userId},update:{},create:{userId:provider.userId}}),hold=await db.walletTransaction.findUniqueOrThrow({where:{reference:request.paymentHoldRef}});await db.$transaction(async tx=>{await tx.walletTransaction.update({where:{id:hold.id},data:{status:'COMPLETED',commissionSnapshot:JSON.stringify(snapshot)}});await tx.walletTransaction.create({data:{walletId:providerWallet.id,type:'CREDIT',amountCents:snapshot.netSettlementCents,reference:`mzansifix-settlement:${request.id}`,status:'COMPLETED',relatedEntityType:'ServiceRequest',relatedEntityId:request.id,commissionSnapshot:JSON.stringify(snapshot)}});await tx.serviceRequest.update({where:{id:request.id},data:{status:'PAYMENT_RELEASED'}});await tx.serviceTransition.create({data:{requestId:request.id,fromState:request.status,toState:'PAYMENT_RELEASED',actorId:req.identity.sub}})});res.json({snapshot});}));
app.post('/api/mzansifix/requests/:id/review',current,asyncRoute(async(req:any,res:any)=>{const request=await ownServiceCustomer(req.params.id,req.identity.sub);assertServiceTransition(request.status,'REVIEWED');const input=z.object({rating:z.number().int().min(1).max(5),comment:z.string().max(500).optional()}).parse(req.body),provider=await db.serviceProvider.findUniqueOrThrow({where:{id:request.providerId!}});const review=await db.$transaction(async tx=>{const created=await tx.serviceReview.create({data:{requestId:request.id,authorId:req.identity.sub,subjectId:provider.userId,rating:input.rating,comment:input.comment}});await tx.serviceRequest.update({where:{id:request.id},data:{status:'REVIEWED'}});await tx.serviceTransition.create({data:{requestId:request.id,fromState:request.status,toState:'REVIEWED',actorId:req.identity.sub}});return created});res.status(201).json({review});}));
app.post('/api/mzansiwork/workers',current,asyncRoute(async(req:any,res:any)=>{const input=workerSchema.parse(req.body),data={...input,skills:JSON.stringify(input.skills),qualifications:JSON.stringify(input.qualifications),certificateRefs:JSON.stringify(input.certificateRefs),verificationStatus:'PENDING' as const};res.status(201).json({worker:await db.workerProfile.upsert({where:{userId:req.identity.sub},update:data,create:{...data,userId:req.identity.sub}})});}));
app.post('/api/mzansiwork/jobs',current,asyncRoute(async(req:any,res:any)=>{const input=jobSchema.parse(req.body);await requireBusiness(input.businessId,req.identity.sub);if(input.endsAt&&new Date(input.endsAt)<=new Date(input.startsAt))return res.status(400).json({error:'Job end must be after start'});const job=await db.jobPost.create({data:{...input,requiredSkills:JSON.stringify(input.requiredSkills),startsAt:new Date(input.startsAt),endsAt:input.endsAt?new Date(input.endsAt):undefined}});res.status(201).json({job});}));
app.get('/api/mzansiwork/jobs',current,asyncRoute(async(req:any,res:any)=>{const worker=await db.workerProfile.findUniqueOrThrow({where:{userId:req.identity.sub}}),workerSkills=JSON.parse(worker.skills) as string[];const jobs=await db.jobPost.findMany({where:{status:'OPEN',startsAt:{gte:new Date(Date.now()-86400000)}}});res.json({jobs:jobs.map(job=>({...job,matchScore:matchScore(JSON.parse(job.requiredSkills),workerSkills,worker.verificationStatus==='VERIFIED',worker.availability.length>0,worker.experienceYears)})).sort((a,b)=>b.matchScore-a.matchScore)});}));
app.post('/api/mzansiwork/jobs/:id/apply',current,asyncRoute(async(req:any,res:any)=>{const worker=await db.workerProfile.findUniqueOrThrow({where:{userId:req.identity.sub}}),job=await db.jobPost.findUniqueOrThrow({where:{id:req.params.id}});if(job.status!=='OPEN')return res.status(409).json({error:'Job is not open'});const {coverNote}=z.object({coverNote:z.string().max(1000).optional()}).parse(req.body),score=matchScore(JSON.parse(job.requiredSkills),JSON.parse(worker.skills),worker.verificationStatus==='VERIFIED',worker.availability.length>0,worker.experienceYears);res.status(201).json({application:await db.jobApplication.create({data:{jobId:job.id,workerId:req.identity.sub,coverNote,matchScore:score}})});}));
app.get('/api/mzansiwork/jobs/:id/applications',current,asyncRoute(async(req:any,res:any)=>{const job=await ownEmployerJob(req.params.id,req.identity.sub);res.json({applications:await db.jobApplication.findMany({where:{jobId:job.id},orderBy:{matchScore:'desc'},select:{id:true,status:true,matchScore:true,coverNote:true,createdAt:true,worker:{select:{id:true,firstName:true,lastName:true,workerProfile:{select:{location:true,skills:true,experienceYears:true,qualifications:true,verificationStatus:true,availability:true,rateExpectationCents:true}}}}}})});}));
app.post('/api/mzansiwork/applications/:id/select',current,asyncRoute(async(req:any,res:any)=>{const application=await db.jobApplication.findUniqueOrThrow({where:{id:req.params.id},include:{job:true,worker:{include:{workerProfile:true}}}});await ownEmployerJob(application.jobId,req.identity.sub);if(!application.worker.workerProfile)return res.status(409).json({error:'Worker profile is incomplete'});const selected=await db.$transaction(async tx=>{await tx.jobApplication.update({where:{id:application.id},data:{status:'SELECTED'}});return tx.workAssignment.create({data:{jobId:application.jobId,workerId:application.worker.workerProfile!.id,status:'PENDING_ACCEPTANCE'}})});res.status(201).json({assignment:selected});}));
app.post('/api/mzansiwork/assignments/:id/accept',current,asyncRoute(async(req:any,res:any)=>{const assignment=await ownWorkerAssignment(req.params.id,req.identity.sub);if(assignment.status!=='PENDING_ACCEPTANCE')return res.status(409).json({error:'Assignment is not awaiting acceptance'});const result=await db.$transaction(async tx=>{await tx.jobApplication.update({where:{jobId_workerId:{jobId:assignment.jobId,workerId:req.identity.sub}},data:{status:'ACCEPTED'}});return tx.workAssignment.update({where:{id:assignment.id},data:{status:'SCHEDULED'}})});res.json({assignment:result});}));
app.post('/api/mzansiwork/assignments/:id/check-in',current,asyncRoute(async(req:any,res:any)=>{const assignment=await ownWorkerAssignment(req.params.id,req.identity.sub);if(!['SCHEDULED','IN_PROGRESS'].includes(assignment.status))return res.status(409).json({error:'Assignment cannot be checked into'});const location=z.object({latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional()}).parse(req.body);const open=await db.workTimeEntry.findFirst({where:{assignmentId:assignment.id,checkedOutAt:null}});if(open)return res.status(409).json({error:'An active check-in already exists'});const entry=await db.$transaction(async tx=>{await tx.workAssignment.update({where:{id:assignment.id},data:{status:'IN_PROGRESS'}});return tx.workTimeEntry.create({data:{assignmentId:assignment.id,checkedInAt:new Date(),...location}})});res.status(201).json({entry});}));
app.post('/api/mzansiwork/assignments/:id/check-out',current,asyncRoute(async(req:any,res:any)=>{const assignment=await ownWorkerAssignment(req.params.id,req.identity.sub),entry=await db.workTimeEntry.findFirst({where:{assignmentId:assignment.id,checkedOutAt:null},orderBy:{checkedInAt:'desc'}});if(!entry)return res.status(409).json({error:'No active check-in exists'});const checkedOutAt=new Date(),minutes=workedMinutes(entry.checkedInAt,checkedOutAt);res.json({entry:await db.workTimeEntry.update({where:{id:entry.id},data:{checkedOutAt,minutes}}),minutes});}));
app.post('/api/mzansiwork/assignments/:id/complete',current,asyncRoute(async(req:any,res:any)=>{const assignment=await db.workAssignment.findUniqueOrThrow({where:{id:req.params.id},include:{job:true,timeEntries:true}});await ownEmployerJob(assignment.jobId,req.identity.sub);if(assignment.status!=='IN_PROGRESS'||assignment.timeEntries.some(e=>!e.checkedOutAt))return res.status(409).json({error:'Completed, closed time entries are required'});const minutes=assignment.timeEntries.reduce((sum,e)=>sum+(e.minutes||0),0),payment=expectedPayment(minutes,assignment.job.rateCents,assignment.job.rateUnit);res.json({assignment:await db.workAssignment.update({where:{id:assignment.id},data:{status:'COMPLETED',expectedPaymentCents:payment}}),minutes,expectedPaymentCents:payment});}));
app.get('/api/mzansiwork/history',current,asyncRoute(async(req:any,res:any)=>{const worker=await db.workerProfile.findUniqueOrThrow({where:{userId:req.identity.sub}});res.json({assignments:await db.workAssignment.findMany({where:{workerId:worker.id},include:{job:true,timeEntries:true},orderBy:{createdAt:'desc'}})});}));
app.post('/api/suppliers',current,asyncRoute(async(req:any,res:any)=>{const input=supplierProfileSchema.parse(req.body);await requireBusiness(input.businessId,req.identity.sub);const data={businessId:input.businessId,serviceAreas:JSON.stringify(input.serviceAreas),description:input.description,verificationStatus:'PENDING' as const};res.status(201).json({supplier:await db.supplierProfile.upsert({where:{businessId:input.businessId},update:data,create:data})});}));
app.post('/api/suppliers/:id/products',current,asyncRoute(async(req:any,res:any)=>{const supplier=await ownSupplier(req.params.id,req.identity.sub),input=supplierProductSchema.parse(req.body);res.status(201).json({product:await db.supplierProduct.create({data:{...input,supplierId:supplier.id}})});}));
app.post('/api/suppliers/:id/promotions',current,asyncRoute(async(req:any,res:any)=>{const supplier=await ownSupplier(req.params.id,req.identity.sub),input=z.object({title:z.string().min(2).max(120),description:z.string().max(500).optional(),discountBasisPoints:z.number().int().min(1).max(10000),startsAt:z.string().datetime(),endsAt:z.string().datetime()}).parse(req.body);if(new Date(input.endsAt)<=new Date(input.startsAt))return res.status(400).json({error:'Promotion end must be after start'});res.status(201).json({promotion:await db.supplierPromotion.create({data:{...input,startsAt:new Date(input.startsAt),endsAt:new Date(input.endsAt),supplierId:supplier.id}})});}));
app.get('/api/suppliers/search',current,asyncRoute(async(req:any,res:any)=>{const category=typeof req.query.category==='string'?req.query.category:undefined,name=typeof req.query.q==='string'?req.query.q:undefined;res.json({products:await db.supplierProduct.findMany({where:{active:true,availableQuantity:{gt:0},category:category?{contains:category}:undefined,name:name?{contains:name}:undefined,supplier:{verificationStatus:'VERIFIED'}},include:{supplier:{include:{business:true,promotions:{where:{active:true,startsAt:{lte:new Date()},endsAt:{gte:new Date()}}}}}},orderBy:{wholesalePriceCents:'asc'}})});}));
app.post('/api/suppliers/:id/favourite',current,asyncRoute(async(req:any,res:any)=>{const {businessId}=z.object({businessId:z.string()}).parse(req.body);await requireBusiness(businessId,req.identity.sub);res.status(201).json({favourite:await db.supplierFavourite.upsert({where:{businessId_supplierId:{businessId,supplierId:req.params.id}},update:{},create:{businessId,supplierId:req.params.id}})});}));
app.post('/api/supplier-orders',current,asyncRoute(async(req:any,res:any)=>{const input=supplierOrderSchema.parse(req.body);await requireBusiness(input.buyerId,req.identity.sub);const supplier=await db.supplierProfile.findUniqueOrThrow({where:{id:input.supplierId},include:{business:true}});if(supplier.verificationStatus!=='VERIFIED')return res.status(409).json({error:'Supplier is not verified'});const products=await db.supplierProduct.findMany({where:{id:{in:input.items.map(i=>i.productId)},supplierId:supplier.id,active:true}});if(products.length!==new Set(input.items.map(i=>i.productId)).size)return res.status(400).json({error:'Invalid supplier products'});const lines=input.items.map(item=>{const product=products.find(p=>p.id===item.productId)!;return{productId:product.id,productName:product.name,quantity:item.quantity,unitPriceCents:product.wholesalePriceCents,minimumQuantity:product.minimumQuantity,availableQuantity:product.availableQuantity}}),subtotalCents=orderTotal(lines);const order=await db.$transaction(async tx=>{for(const line of lines)await tx.supplierProduct.update({where:{id:line.productId},data:{availableQuantity:{decrement:line.quantity}}});return tx.supplierOrder.create({data:{buyerId:input.buyerId,supplierId:input.supplierId,deliveryAddress:input.deliveryAddress,subtotalCents,items:{create:lines.map(({minimumQuantity,availableQuantity,...line})=>line)}},include:{items:true}})});res.status(201).json({order});}));
app.post('/api/supplier-orders/:id/accept',current,asyncRoute(async(req:any,res:any)=>{const order=await db.supplierOrder.findUniqueOrThrow({where:{id:req.params.id},include:{supplier:{include:{business:true}},items:true}});await requireBusiness(order.supplier.businessId,req.identity.sub);if(order.status!=='PLACED')return res.status(409).json({error:'Order is not awaiting acceptance'});const result=await db.$transaction(async tx=>{const request=await tx.stockRequest.create({data:{businessId:order.buyerId,supplierName:order.supplier.business.name,deliveryAddress:order.deliveryAddress,status:'SEARCHING_DRIVER',estimatedTotalCents:order.subtotalCents,items:{create:order.items.map(i=>({productName:i.productName,quantity:i.quantity,estimatedUnitCents:i.unitPriceCents}))}}});return tx.supplierOrder.update({where:{id:order.id},data:{status:'READY_FOR_PICKUP',stockRequestId:request.id},include:{items:true,stockRequest:true}})});res.json({order:result});}));
app.get('/api/supplier-orders/business/:businessId',current,asyncRoute(async(req:any,res:any)=>{await requireBusiness(req.params.businessId,req.identity.sub);res.json({orders:await db.supplierOrder.findMany({where:{buyerId:req.params.businessId},include:{items:true,supplier:{include:{business:true}},stockRequest:true},orderBy:{createdAt:'desc'}})});}));
async function ownSupplier(id:string,userId:string){const supplier=await db.supplierProfile.findFirst({where:{id,business:{members:{some:{userId}}}}});if(!supplier)throw Object.assign(new Error('Supplier access required'),{status:403});return supplier}
async function ownEmployerJob(id:string,userId:string){const job=await db.jobPost.findFirst({where:{id,business:{members:{some:{userId}}}}});if(!job)throw Object.assign(new Error('Employer job not found'),{status:404});return job}
async function ownWorkerAssignment(id:string,userId:string){const assignment=await db.workAssignment.findFirst({where:{id,worker:{userId}},include:{job:true,timeEntries:true}});if(!assignment)throw Object.assign(new Error('Worker assignment not found'),{status:404});return assignment}
async function ownServiceCustomer(id:string,userId:string){const request=await db.serviceRequest.findFirst({where:{id,customerId:userId}});if(!request)throw Object.assign(new Error('Customer request not found'),{status:404});return request}
async function transitionService(request:any,toState:any,actorId:string){return db.$transaction(async tx=>{const updated=await tx.serviceRequest.update({where:{id:request.id},data:{status:toState}});await tx.serviceTransition.create({data:{requestId:request.id,fromState:request.status,toState,actorId}});return updated})}
async function requireBusiness(businessId:string,userId:string){const member=await db.businessMember.findUnique({where:{businessId_userId:{businessId,userId}}});if(!member)throw Object.assign(new Error('Business access required'),{status:403});return member}
async function ownDriverRequest(id:string,userId:string){const request=await db.stockRequest.findFirst({where:{id,driverId:userId},include:{items:true}});if(!request)throw Object.assign(new Error('Assigned request not found'),{status:404});return request}
async function ownBusinessRequest(id:string,userId:string){const request=await db.stockRequest.findFirst({where:{id,business:{members:{some:{userId}}}},include:{items:true}});if(!request)throw Object.assign(new Error('Business request not found'),{status:404});return request}
function safe(u:any){return{id:u.id,email:u.email,phone:u.phone,firstName:u.firstName,lastName:u.lastName,status:u.status};}
const publicDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'public');app.use(express.static(publicDir));app.use((_req,res)=>res.sendFile(path.join(publicDir,'index.html')));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);if(err?.name==='ZodError')return res.status(400).json({error:'Please check the submitted fields',details:err.issues});res.status(err?.status||500).json({error:err?.status?err.message:'Unexpected server error'});});
if(process.env.NODE_ENV!=='test')app.listen(Number(process.env.PORT||3000),()=>console.log(`HYDRA CORE running on ${process.env.PORT||3000}`));
export {app};
