import { createHmac, timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
export type CommissionInput={grossCents:number;commissionBasisPoints:number;paymentFeeCents:number;vatBasisPoints:number};
export function calculateCommission(input:CommissionInput){const platformCommissionCents=Math.round(input.grossCents*input.commissionBasisPoints/10000),vatCents=Math.round(platformCommissionCents*input.vatBasisPoints/10000),providerAmountCents=input.grossCents-platformCommissionCents-input.paymentFeeCents-vatCents;if(providerAmountCents<0)throw new Error('Fees exceed gross amount');return{grossCents:input.grossCents,platformCommissionCents,paymentFeeCents:input.paymentFeeCents,vatCents,providerAmountCents,netSettlementCents:providerAmountCents}}
export const paymentRequestSchema=z.object({amountCents:z.number().int().positive(),currency:z.literal('ZAR').default('ZAR'),relatedEntityType:z.string().max(60).optional(),relatedEntityId:z.string().max(100).optional(),idempotencyKey:z.string().min(8).max(120)});
export interface PaymentProvider{readonly name:string;initiate(input:{amountCents:number;currency:string;idempotencyKey:string}):Promise<{providerReference:string;status:'PENDING'}>;verify(reference:string):Promise<'PENDING'|'SUCCEEDED'|'FAILED'>;refund(reference:string,amountCents:number):Promise<{providerReference:string;status:'PENDING'}>;verifyWebhook(rawBody:string,signature:string):boolean}
export class SandboxPaymentProvider implements PaymentProvider{readonly name='sandbox';constructor(private readonly webhookSecret:string){}async initiate(input:{amountCents:number;currency:string;idempotencyKey:string}){return{providerReference:`sbx_${input.idempotencyKey}`,status:'PENDING' as const}}async verify(_reference:string){return'PENDING' as const}async refund(reference:string,_amountCents:number){return{providerReference:`refund_${reference}`,status:'PENDING' as const}}verifyWebhook(rawBody:string,signature:string){const expected=createHmac('sha256',this.webhookSecret).update(rawBody).digest('hex'),a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b)}}
export function getPaymentProvider(){if(process.env.PAYMENT_MODE!=='sandbox')throw new Error('No production payment provider is configured');const secret=process.env.PAYMENT_WEBHOOK_SECRET;if(!secret||secret.length<24)throw new Error('PAYMENT_WEBHOOK_SECRET must contain at least 24 characters');return new SandboxPaymentProvider(secret)}
export const signedAmount=(type:string,amountCents:number)=>['CREDIT','RELEASE','REFUND','ADJUSTMENT'].includes(type)?amountCents:-amountCents;
