export const en={
'brand.name':'HYDRA WORKS','brand.tagline':'One account. Five platforms. One ecosystem.','brand.description':'Build, trade, deliver and grow through one trusted South African digital identity.',
'auth.signIn':'Sign in','auth.createAccount':'Create account','auth.firstName':'First name','auth.lastName':'Last name','auth.email':'Email address','auth.mobile':'Mobile number','auth.province':'Province','auth.selectProvince':'Select province','auth.primaryRole':'Primary role','auth.password':'Password','auth.signInSecurely':'Sign in securely','auth.createHydraId':'Create HYDRA ID','auth.security':'Your password is encrypted. Sessions use secure, HTTP-only cookies.',
'role.customer':'Customer','role.businessOwner':'Business owner','role.driver':'Driver','role.serviceProvider':'Service provider','role.worker':'Worker','role.supplier':'Supplier',
'nav.overview':'Overview','nav.commandCentre':'Command Centre','nav.subscriptions':'Subscriptions','nav.storefront':'KASIBIZ Storefront','nav.businesses':'My businesses','nav.wallet':'HYDRA Wallet','nav.messages':'Messages','nav.support':'Support','nav.settings':'Settings','nav.signOut':'Sign out',
'dashboard.welcome':'Welcome, {{name}}','dashboard.ecosystem':'YOUR DIGITAL BUSINESS ECOSYSTEM','dashboard.hero':'Everything your business needs, connected by HYDRA ID.','dashboard.viewPlans':'View plans','dashboard.explore':'Explore the ecosystem','dashboard.businessAccounts':'Business accounts','dashboard.noBusiness':'No business is linked yet. Create a business to unlock business services.','dashboard.apiAvailable':'Available through secured APIs','dashboard.openHosting':'Open hosting dashboard →','dashboard.publishStorefront':'Publish your storefront →',
'module.tuckquest':'Stock acquisition & delivery','module.kasibiz':'Business management','module.mzansifix':'Local services','module.mzansiwork':'Jobs & workforce','module.hydrahost':'Domains, websites & business email',
'language.label':'Language','language.reviewPending':'Translation pending review — English is shown for now.'
}as const;
